## DDR4 Interface
set_property PACKAGE_PIN AN7 [get_ports {c0_ddr4_ck_t[0]}]
set_property PACKAGE_PIN AP7 [get_ports {c0_ddr4_ck_c[0]}]
set_property IOSTANDARD DIFF_SSTL12_DCI [ get_ports {c0_ddr4_ck_t[0]} ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports {c0_ddr4_ck_t[0]} ]
set_property IOSTANDARD DIFF_SSTL12_DCI [ get_ports {c0_ddr4_ck_c[0]} ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports {c0_ddr4_ck_c[0]} ]

set_property PACKAGE_PIN AM8 [get_ports {c0_ddr4_adr[0]}]
set_property PACKAGE_PIN AM9 [get_ports {c0_ddr4_adr[1]}]
set_property PACKAGE_PIN AP8 [get_ports {c0_ddr4_adr[2]}]
set_property PACKAGE_PIN AN8 [get_ports {c0_ddr4_adr[3]}]
set_property PACKAGE_PIN AK10 [get_ports {c0_ddr4_adr[4]}]
set_property PACKAGE_PIN AJ10 [get_ports {c0_ddr4_adr[5]}]
set_property PACKAGE_PIN AP9 [get_ports {c0_ddr4_adr[6]}]
set_property PACKAGE_PIN AN9 [get_ports {c0_ddr4_adr[7]}]
set_property PACKAGE_PIN AP10 [get_ports {c0_ddr4_adr[8]}]
set_property PACKAGE_PIN AP11 [get_ports {c0_ddr4_adr[9]}]
set_property PACKAGE_PIN AM10 [get_ports {c0_ddr4_adr[10]}]
set_property PACKAGE_PIN AL10 [get_ports {c0_ddr4_adr[11]}]
set_property PACKAGE_PIN AM11 [get_ports {c0_ddr4_adr[12]}]
set_property PACKAGE_PIN AL11 [get_ports {c0_ddr4_adr[13]}]

set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_adr[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_adr[1]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_adr[2]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_adr[3]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_adr[4]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_adr[5]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_adr[6]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_adr[7]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_adr[8]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_adr[9]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_adr[10]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_adr[11]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_adr[12]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_adr[13]}]

set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[1]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[2]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[3]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[4]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[5]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[6]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[7]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[8]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[9]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[10]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[11]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[12]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[13]}]

set_property PACKAGE_PIN AL3 [get_ports {c0_ddr4_dqs_t[1]}]
set_property PACKAGE_PIN AL2 [get_ports {c0_ddr4_dqs_c[1]}]
set_property PACKAGE_PIN AN6 [get_ports {c0_ddr4_dqs_t[0]}]
set_property PACKAGE_PIN AP6 [get_ports {c0_ddr4_dqs_c[0]}]

set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dqs_t[1]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dqs_c[1]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dqs_t[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dqs_c[0]}]

set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c0_ddr4_dqs_t[1]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c0_ddr4_dqs_c[1]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c0_ddr4_dqs_t[0]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c0_ddr4_dqs_c[0]}]

set_property PACKAGE_PIN AN2 [get_ports {c0_ddr4_dm_dbi_n[1]}]
set_property PACKAGE_PIN AL6 [get_ports {c0_ddr4_dm_dbi_n[0]}]

set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dm_dbi_n[1]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dm_dbi_n[0]}]

set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dm_dbi_n[1]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dm_dbi_n[0]}]

set_property PACKAGE_PIN AN3 [get_ports {c0_ddr4_dq[15]}]
set_property PACKAGE_PIN AP3 [get_ports {c0_ddr4_dq[14]}]
set_property PACKAGE_PIN AM1 [get_ports {c0_ddr4_dq[13]}]
set_property PACKAGE_PIN AN1 [get_ports {c0_ddr4_dq[12]}]
set_property PACKAGE_PIN AK1 [get_ports {c0_ddr4_dq[11]}]
set_property PACKAGE_PIN AL1 [get_ports {c0_ddr4_dq[10]}]
set_property PACKAGE_PIN AK3 [get_ports {c0_ddr4_dq[9]}]
set_property PACKAGE_PIN AK2 [get_ports {c0_ddr4_dq[8]}]
set_property PACKAGE_PIN AM6 [get_ports {c0_ddr4_dq[7]}]
set_property PACKAGE_PIN AM5 [get_ports {c0_ddr4_dq[6]}]
set_property PACKAGE_PIN AP5 [get_ports {c0_ddr4_dq[5]}]
set_property PACKAGE_PIN AP4 [get_ports {c0_ddr4_dq[4]}]
set_property PACKAGE_PIN AM4 [get_ports {c0_ddr4_dq[3]}]
set_property PACKAGE_PIN AN4 [get_ports {c0_ddr4_dq[2]}]
set_property PACKAGE_PIN AK5 [get_ports {c0_ddr4_dq[1]}]
set_property PACKAGE_PIN AK4 [get_ports {c0_ddr4_dq[0]}]

set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq[15]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq[14]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq[13]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq[12]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq[11]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq[10]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq[9]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq[8]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq[7]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq[6]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq[5]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq[4]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq[3]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq[2]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq[1]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_dq[0]}]

set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[15]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[14]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[13]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[12]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[11]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[10]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[9]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[8]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[7]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[6]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[5]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[4]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[3]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[2]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[1]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[0]}]

## WE_N Signal
set_property PACKAGE_PIN AJ7 [get_ports {c0_ddr4_adr[14]}]
## CAS_N Signal
set_property PACKAGE_PIN AL5 [get_ports {c0_ddr4_adr[15]}]
## RAS_N Signal
set_property PACKAGE_PIN AJ9 [get_ports {c0_ddr4_adr[16]}]

set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_adr[14]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_adr[15]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_ddr4_adr[16]}]

set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[14]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[15]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[16]}]

set_property PACKAGE_PIN AK8 [get_ports {c0_ddr4_act_n}]
set_property IOSTANDARD SSTL12_DCI [ get_ports {c0_ddr4_act_n} ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports {c0_ddr4_act_n} ]

set_property PACKAGE_PIN AH9 [get_ports {c0_ddr4_reset_n}]
set_property IOSTANDARD LVCMOS18 [ get_ports {c0_ddr4_reset_n} ]
set_property DRIVE 8 [get_ports {c0_ddr4_reset_n}]

set_property PACKAGE_PIN AK9 [get_ports {c0_ddr4_odt[0]}]
set_property IOSTANDARD SSTL12_DCI [ get_ports {c0_ddr4_odt[0]} ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports {c0_ddr4_odt[0]} ]

set_property PACKAGE_PIN AP2 [get_ports {c0_ddr4_cs_n[0]}]
set_property IOSTANDARD SSTL12_DCI [ get_ports {c0_ddr4_cs_n[0]} ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports {c0_ddr4_cs_n[0]} ]

set_property PACKAGE_PIN AM3 [get_ports {c0_ddr4_cke[0]}]
set_property IOSTANDARD SSTL12_DCI [ get_ports {c0_ddr4_cke[0]} ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports {c0_ddr4_cke[0]} ]

set_property PACKAGE_PIN AK12 [get_ports {c0_ddr4_ba[0]}]
set_property IOSTANDARD SSTL12_DCI [ get_ports {c0_ddr4_ba[0]} ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports {c0_ddr4_ba[0]} ]

set_property PACKAGE_PIN AJ12 [get_ports {c0_ddr4_ba[1]}]
set_property IOSTANDARD SSTL12_DCI [ get_ports {c0_ddr4_ba[1]} ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports {c0_ddr4_ba[1]} ]

set_property PACKAGE_PIN AK7 [get_ports {c0_ddr4_bg[0]}]
set_property IOSTANDARD SSTL12_DCI [ get_ports {c0_ddr4_bg[0]} ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports {c0_ddr4_bg[0]} ]